import json, os, re, collections
T = os.environ['TEMP']
s = json.load(open(T + '/schema.json', encoding='utf-8'))
cols = collections.defaultdict(list)
for c in s['cols']:
    cols[c['t']].append(c)
fks = collections.defaultdict(list)
for f in s['fks']:
    fks[f['t']].append(f)
kind = {t['t']: t['tt'] for t in s['tables']}

D = {
'users': 'Core accounts for all roles (login, role, status, session, account lockout, FCM token, Telegram id)',
'roles': 'The six role definitions',
'students': 'Student profile: code, level, program, device binding, reference face embedding',
'teachers': 'Teacher profile, plus advisor fields (advisor_branch / advisor_year)',
'parents': 'Parent profile',
'heads': 'Heads of department and their department link',
'admins': 'Administrator profile',
'parent_students': 'Parent-to-student links (many-to-many)',
'departments': 'Academic departments, plus the offline attendance sync policy (offline_sync_policy)',
'programs': 'Programs / specializations belonging to departments',
'courses': 'Courses (title, code, hours, weight, year, semester)',
'course_program': 'Course-to-program links',
'course_departments': 'Course-to-department links',
'course_teachers': 'Teachers assigned to courses, with a role (e.g. advisor)',
'semesters': 'Academic semesters and the active-semester flag',
'enrollments': 'Student enrollment in courses per semester',
'subjects': 'Subjects (legacy / auxiliary structure)',
'schedules': 'Weekly class timetable (day, time, room, class group)',
'head_schedule_entries': 'Timetable entries created by the head of department',
'exams': 'Exam timetable',
'lessons': 'Lectures / sessions (file, video, teacher, course); one attendance session is created per lesson',
'resources': 'Course files and references',
'attendance_sessions': 'Attendance session: rotating QR token, location and radius, validity',
'attendance': 'Attendance log: status, device, location, face match score, reject reason, excuse',
'student_warnings': 'Automatic absence warnings (first / second / final)',
'assignments': 'Assignments',
'assignment_submissions': 'Student submissions and grading',
'quizzes': 'Online quizzes', 'quiz_questions': 'Quiz questions', 'quiz_options': 'Quiz question options',
'grades': 'Exam grades (legacy system)',
'grade_events': 'Assessment events (exam / quiz / oral) with date, time and maximum score',
'grade_entries': 'Per-student scores for each assessment event',
'grade_report_requests': 'Head-of-department requests for grade reports from teachers',
'performance_reports': 'Performance reports',
'report_requests': 'Behavioral report requests (from head or parent) and head notes',
'admin_generated_reports': 'Log of reports generated by the administration',
'leave_requests': 'Leave requests (student -> parent -> head -> affairs)',
'absence_requests': 'Absence permission requests',
'student_requests': 'Student service requests (appeal, documents, make-up exam, device unlock)',
'photo_change_requests': 'Requests to change the student reference photo',
'parent_meeting_requests': 'Meeting requests from parents',
'parent_summons': 'Parent summons (manual, or automatic after 10 absence days)',
'messages': 'Chat messages (attachments, reply, forward, delete, disappearing, delivery/read)',
'groups': 'Chat groups', 'group_user': 'Group members', 'chats': 'Legacy chat table',
'notifications': 'In-system notifications (type, category, related id)',
'announcements': 'Announcements and activities (target audience, images, link, event details)',
'calendar_events': 'Academic calendar events',
'university_ids': 'Pre-registered university IDs created by Affairs before a student registers',
'otp_codes': 'Email verification codes (current)', 'otps': 'Verification codes (legacy)',
'user_activities': 'User activity log (audit)', 'user_activity': 'Legacy activity log',
'system_settings': 'System settings (theme)',
'personal_access_tokens': 'Sanctum tokens', 'sessions': 'Web sessions', 'session': 'Legacy sessions table',
'cache': 'Laravel cache', 'cache_locks': 'Cache locks', 'jobs': 'Queue jobs', 'job_batches': 'Job batches', 'failed_jobs': 'Failed jobs',
'admin_profile_stats_view': 'View: admin profile statistics',
'affairs_dashboard_stats_view': 'View: Affairs dashboard statistics',
'teacher_dashboard_stats_view': 'View: teacher dashboard statistics',
}


def esc(x):
    return '' if x is None else str(x).replace('|', '\\|').replace('\n', ' ')


nbase = len([t for t in kind.values() if t == 'BASE TABLE'])
nview = len([t for t in kind.values() if t != 'BASE TABLE'])
out = ['# Database Dictionary\n',
       f'> Auto-generated from the real migrations (run `php artisan migrate` on an empty database, then read `information_schema`). **{nbase} tables and {nview} views, {len(s["cols"])} columns, {len(s["fks"])} foreign keys.**\n',
       '## Read this first\n',
       '- **Primary keys are custom, not `id`**, in most tables: `user_id`, `student_id`, `teacher_id`, `course_id`, `lesson_id`... (exceptions: `programs.id`, `grade_events.id`, `attendance_sessions.id`).',
       '- **There are more logical relations than declared foreign keys** (only 72 FKs). Much of the linking is done in code with no database constraint, e.g. `parent_students` and `leave_requests.student_id`.',
       '- **Consistency warning:** `parent_students.parent_id/student_id` and `leave_requests.student_id` may hold `users.user_id` or the internal id (`parents.parent_id` / `students.student_id`). The code handles both (see `08-project-status.md`, item B-04).',
       '- Legacy tables still present: `chats`, `user_activity`, `session`, `otps`, `subjects`. They appear unused (verify before dropping).\n',
       '## Relationship diagram (core tables)\n',
       'Shows the most important tables and relations (declared foreign keys plus logical relations documented from the models). Mermaid format, rendered automatically on GitHub and the documentation site.\n',
       '```mermaid', 'erDiagram',
       '    users ||--o| students : "user_id"', '    users ||--o| teachers : "user_id"', '    users ||--o| parents : "user_id"',
       '    users ||--o| heads : "user_id"', '    roles ||--o{ users : "role_id"',
       '    departments ||--o{ programs : "department_id"', '    departments ||--o| heads : "department_id"', '    programs ||--o{ students : "program_id"',
       '    courses }o--o{ programs : "course_program"', '    courses }o--o{ departments : "course_departments"', '    courses }o--o{ teachers : "course_teachers"',
       '    students }o--o{ courses : "enrollments"', '    students }o--o{ parents : "parent_students"',
       '    courses ||--o{ lessons : "course_id"', '    lessons ||--o{ attendance_sessions : "lesson_id"', '    lessons ||--o{ attendance : "lesson_id"',
       '    students ||--o{ attendance : "student_id"', '    students ||--o{ student_warnings : "student_id"',
       '    courses ||--o{ assignments : "course_id"', '    assignments ||--o{ assignment_submissions : "assignment_id"', '    students ||--o{ assignment_submissions : "student_id"',
       '    courses ||--o{ grade_events : "course_id"', '    grade_events ||--o{ grade_entries : "grade_event_id"', '    students ||--o{ grade_entries : "student_id"',
       '    users ||--o{ messages : "sender / receiver"', '    users ||--o{ notifications : "user_id"', '    students ||--o{ parent_summons : "student_id"',
       '    semesters ||--o{ enrollments : "semester_id"',
       '```\n',
       '## Table index\n', '| Table | Type | Description |', '|---|---|---|']
for t in sorted(kind):
    out.append(f'| [`{t}`](#{t}) | {"View" if kind[t] != "BASE TABLE" else "Table"} | {D.get(t, "-")} |')
out.append('\n---\n')
for t in sorted(kind):
    out.append(f'## {t}\n')
    if t in D:
        out.append(f'{D[t]}\n')
    out.append('| Column | Type | Null | Default | Key | Notes |\n|---|---|---|---|---|---|')
    for c in cols[t]:
        k = {'PRI': 'PK', 'UNI': 'UNIQUE', 'MUL': 'INDEX'}.get(c['k'], '')
        note = c['cm'] or ''
        if 'auto_increment' in (c['e'] or ''):
            note = (note + ' auto-increment').strip()
        out.append(f"| `{c['c']}` | `{esc(c['ty'])}` | {'Yes' if c['n'] == 'YES' else 'No'} | {esc(c['d'])} | {k} | {esc(note)} |")
    if fks[t]:
        out.append('\n**Foreign keys:** ' + ', '.join(f"`{f['c']}` -> `{f['rt']}.{f['rc']}`" for f in fks[t]))
    out.append('')
os.makedirs('docs/en', exist_ok=True)
open('docs/en/03-database.md', 'w', encoding='utf-8', newline='\n').write('\n'.join(out))

# ---------------- API ----------------
r = json.load(open(T + '/routes.json', encoding='utf-8'))
api = [x for x in r if x['uri'].startswith('api/')]


def roles(m):
    for x in m:
        mm = re.search(r'RoleMiddleware:(.+)', x)
        if mm:
            return mm.group(1)
    return None


def auth(x):
    m = x['middleware']
    if any('Authenticate:sanctum' in y for y in m):
        rr = roles(m)
        return ('Auth + role: ' + rr) if rr else 'Auth (any role)'
    return 'Public'


def thr(x):
    for y in x['middleware']:
        mm = re.search(r'ThrottleRequests:(.+)', y)
        if mm and mm.group(1) != 'api':
            return ' (throttle:' + mm.group(1) + ')'
    return ''


def short(a):
    a = a.replace('App\\Http\\Controllers\\', '')
    return '`' + a + '`' if '@' in a else '`Closure`'


groups = collections.OrderedDict()
groups['Public (no authentication)'] = lambda x: auth(x) == 'Public'
groups['Shared (authentication only)'] = lambda x: auth(x) == 'Auth (any role)'


def pref(p):
    return lambda x: x['uri'].startswith('api/' + p + '/') and auth(x) != 'Public'


for lbl, p in [('Student', 'student'), ('Teacher', 'teacher'), ('Head of department', 'department-head'), ('Admin', 'admin'), ('Parent', 'parent'), ('Affairs', 'affairs')]:
    groups[lbl + f' (`/api/{p}/*`)'] = pref(p)
used = set()
sections = []
for lbl, f in groups.items():
    rows = [x for x in api if id(x) not in used and f(x)]
    for x in rows:
        used.add(id(x))
    sections.append((lbl, rows))
rest = [x for x in api if id(x) not in used]
if rest:
    sections.append(('Other', rest))
tot = len(api)
o = ['# API Reference\n',
     f'> Auto-generated from `php artisan route:list` ({tot} endpoints under `/api`). **Base:** `<SERVER>/api` (local example: `http://127.0.0.1:8000/api`).\n',
     '## General usage\n',
     '- **Authentication:** Laravel Sanctum. After `POST /api/login` a `token` is returned and must be sent on every request: `Authorization: Bearer <token>` with `Accept: application/json`.',
     '- **Single session:** logging in from a new device is refused while another session is active (`423`). A token that was invalidated receives `401` with `error_code = LOGGED_IN_ELSEWHERE`.',
     '- **Roles:** `student`, `teacher`, `head` (head of department), `admin`, `parent`, `affairs`. A disallowed role gets `403`.',
     '- **Rate limits:** a global `throttle:api` (240 requests/minute per user). Login and OTP routes have stricter limits (shown in the table). Exceeding returns `429`.',
     '- **Response shape:** JSON, usually `{ "success": true|false, "message": "...", "data": ... }`. Errors: `422` validation, `403` permission, `404` not found, `423` account locked or session occupied.',
     '- **Encoding:** UTF-8; Arabic text is returned unescaped.',
     '- **Note:** handler names (`Controller@method`) are descriptive and are the starting point for reading each endpoint\'s logic in code.\n',
     '## Index\n']
for lbl, rows in sections:
    o.append(f'- {lbl}: **{len(rows)}**')
o.append('')
for lbl, rows in sections:
    o.append(f'\n## {lbl}\n\n| Method | Path | Handler | Access |\n|---|---|---|---|')
    for x in sorted(rows, key=lambda z: (z['uri'], z['method'])):
        m = x['method'].replace('GET|HEAD', 'GET')
        o.append(f"| {m} | `/{x['uri']}` | {short(x['action'])} | {auth(x)}{thr(x)} |")
open('docs/en/04-api-reference.md', 'w', encoding='utf-8', newline='\n').write('\n'.join(o))
print('done', tot)
